"""add llm_requests table

Revision ID: 2f4b331294c3
Revises: bc7168e6f5ba
Create Date: 2026-08-20 15:39:43.951242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4b331294c3'
down_revision: Union[str, Sequence[str], None] = 'bc7168e6f5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_requests',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', name='llm_request_status'), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_requests_user_id_users')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_llm_requests'))
    )
    op.create_index(op.f('ix_llm_requests_trace_id'), 'llm_requests', ['trace_id'], unique=False)
    op.create_index(op.f('ix_llm_requests_user_id'), 'llm_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_requests_user_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_trace_id'), table_name='llm_requests')
    op.drop_table('llm_requests')
    # ### end Alembic commands ###
